# 1. Usa una imagen base con Node.js
FROM node:20

# 2. Crea una carpeta dentro del contenedor
WORKDIR /app

# 3. Copia los archivos de tu proyecto al contenedor
COPY package*.json ./
COPY tsconfig.json ./
COPY . .

# 4. Instala las dependencias
RUN npm install

# 5. Expone el puerto donde corre tu backend
EXPOSE 3001

# 6. Comando para iniciar el servidor en desarrollo
CMD ["npm", "run", "dev"]
